# Generated by Django 4.0.2 on 2022-04-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
