# Generated by Django 4.0.2 on 2022-05-11 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contactemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactemail',
            name='date_sent',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 11, 1, 40, 25, 11858)),
        ),
    ]
