# Generated by Django 4.0.2 on 2022-05-11 01:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contactemail_date_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactemail',
            name='date_sent',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
