# Generated by Django 4.0.2 on 2022-05-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_instrument_student_repairinfo_previousloaninfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='instrument_image',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
    ]
