# Generated by Django 4.0.2 on 2022-05-23 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_instrument_instrument_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='schooldistrict',
            name='name',
            field=models.CharField(default='N/A', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='schoolsite',
            name='district',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='district', to='api.schooldistrict'),
        ),
        migrations.AddField(
            model_name='schoolsite',
            name='name',
            field=models.CharField(default='N/A', max_length=100, unique=True),
        ),
    ]
