# Generated by Django 4.0.2 on 2022-05-24 19:21

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_schoolsite_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldistrict',
            name='district_code',
            field=models.CharField(default=api.models.unique_id, max_length=10, unique=True),
        ),
    ]
