# Generated by Django 4.0.2 on 2022-05-24 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_schooldistrict_district_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsite',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='site', to='api.schooldistrict'),
        ),
    ]
