# Generated by Django 4.0.2 on 2022-05-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_schoolsite_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='school_district',
            field=models.CharField(default='district', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='school_site',
            field=models.CharField(default='site', max_length=100),
        ),
    ]
