# Generated by Django 4.0.2 on 2022-06-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_customuser_school_district_customuser_school_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldistrict',
            name='verify_district_email',
            field=models.CharField(default='enter "@" followed by district email', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='schooldistrict',
            name='name',
            field=models.CharField(default='enter district name here', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolsite',
            name='name',
            field=models.CharField(default='enter school site here', max_length=100, unique=True),
        ),
    ]
