# Generated by Django 4.0.2 on 2022-06-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_schooldistrict_verify_district_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooldistrict',
            name='verify_district_email',
            field=models.CharField(default='enter what is followed by "@" for district email', max_length=100, unique=True),
        ),
    ]
