# Generated by Django 4.0.2 on 2022-07-21 01:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_previousloaninfo_accept_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentloaninfo',
            name='accept_contract',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='currentloaninfo',
            name='is_returned',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='currentloaninfo',
            name='loan_start',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='currentloaninfo',
            name='parent_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='currentloaninfo',
            name='parent_first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='currentloaninfo',
            name='parent_last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='currentloaninfo',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='currentloaninfo',
            name='student_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='currentloaninfo',
            name='student_first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='currentloaninfo',
            name='student_last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
